[loading_options]
barcodes_filename = "custom_guppy_v2_RBC.fasta"
double_variants_frontrear = false

# ############### Native barcoding kit ###############

[arrangement]
name = "custom_guppy_v1_RBC"
id_pattern = "RB%02i"
compatible_kits = ["RBC_v2"]
first_index = 1
last_index = 3
kit = "RBC_v2"
normalised_id_pattern = "barcode%02i"
scoring_function = "MAX"

barcode1_pattern = "RB%02i"
barcode2_pattern = "RB%02i"