####################
#
# Barcode Design 2
#
####################
#
#  2-Barcode Arrangement Variant 1:
#  
#         BCXX_1st                           BCXX_2nd
#  FWD  >-=====------------------------------=====-\
#                                                   |
#  REV  <-=====------------------------------=====-/
#         BCXX_1st                           BCXX_2nd
#
#  leads to basecall BCXX_1st_FWD----------BCXX_2nd_REV
#
###
#
#  2-Barcode Arrangement Variant 2:
#
#     BCXX_1st                           BCXX_2nd
#   /-=====------------------------------=====->  REV
#  |
#   \-=====------------------------------=====-<  FWD
#     BCXX_1st                           BCXX_2nd
#
#  leads to basecall BCXX_2nd_FWD----------BCXX_1st_REV
#
#  the sequences BCXX_1st and BCXX_2nd will be equal
#  for most of their parts, especially for the main barcode.
#  They will usually only differ in the rear spacer between
#  barcode and (actual) strand.
#
#  Currently the RV barcodes are not included 
####################

[loading_options]
barcodes_filename = "minion_barcodes.fasta"
double_variants_frontrear = false

# ############### Native barcoding kit ###############

[arrangement]
name = "barcode_arrs_96minion"
id_pattern = "NB%02i"
compatible_kits = ["FBC"]
first_index = 1
last_index = 96
kit = "Well"
normalised_id_pattern = "barcode%02i"
scoring_function = "MAX"
#   mask = "NB_1st"
#   mask2 = "NB_2nd"
#   mask = "CUST"
barcode1_pattern = "NB%02i"
#   barcode2_pattern = "NB%02i"
